# Generated by Django 5.2.15 on 2026-07-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("contenu", models.TextField()),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-cree_le"],
            },
        ),
    ]
